services:
  app:
    container_name: containerize_app_1
    build:
      context: app
    networks:
      - internal
    expose:
      - 8000
    volumes:
      - type: bind
        source: ./app/src
        target: /app
    develop:
      watch:
        - path: ./app/src/requirements.txt
          action: rebuild
  nginx:
    container_name: containerize_nginx_1
    build:
      context: nginx
    networks:
      - external
      - internal
    secrets:
      - source: nginx-cert
        target: &cert-path '/run/secrets/localhost.crt'
        mode: 0440
      - source: nginx-key
        target: &cert-key-path '/run/secrets/localhost.key'
        mode: 0440
    environment:
      APP_HOST: app
      APP_PORT: '8000'
      SSL_APP_CERT_PATH: *cert-path
      SSL_APP_CERT_KEY_PATH: *cert-key-path
    ports:
      - '80:80'
      - '443:443'
    develop:
      watch:
        - path: ./nginx/files/
          action: rebuild  # hack as there's no dedicated 'restart' action
        - path: ./nginx/nginx.conf
          action: rebuild
        - path: ./nginx/templates/
          action: rebuild

networks:
  internal:
    internal: true
  external: {}

secrets:
  nginx-cert:
    file: ./nginx/files/localhost.crt
  nginx-key:
    file: ./nginx/files/localhost.key
