services:
  app:
    container_name: containerize_app_1
    build:
      context: app
    networks:
      - internal
    expose:
      - 8000
  nginx:
    container_name: containerize_nginx_1
    build:
      context: nginx
    networks:
      - external
      - internal
    environment:
      APP_HOST: app
      APP_PORT: '8000'
    ports:
      - '80:80'
      - '443:443'

networks:
  internal:
    internal: true
  external: {}
